default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lumon_development
  pool: 5
  username: lumon
  host: localhost

test:
  <<: *default
  database: lumon_test

production:
  <<: *default
  database: lumon_prod
